body:
  - type: markdown
    attributes:
      value: |
        # Session 1 Grant Application
        感谢您参与 Session 1 的 Grants 申请！请按照以下模板填写您的申请信息。

  - type: input
    id: project-name
    attributes:
      label: 项目名称
      placeholder: 您的项目名称
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: 项目描述
      description: 请详细描述您的项目
      placeholder: |
        - 项目目标
        - 技术架构
        - 创新点
    validations:
      required: true

  - type: textarea
    id: grant-usage
    attributes:
      label: 资金使用计划
      description: 请说明您计划如何使用这笔资金
      placeholder: 详细说明资金分配方案...
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: 项目时间线
      description: 请提供项目开发时间线
      placeholder: |
        第一个月：
        - 任务1
        - 任务2
        
        第二个月：
        - 任务3
        - 任务4
    validations:
      required: true

  - type: textarea
    id: team
    attributes:
      label: 团队介绍
      description: 请介绍您的团队成员及其角色
      placeholder: |
        - 成员1：职责/经验
        - 成员2：职责/经验
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      options:
        - label: 我确认所有提供的信息都是真实的
          required: true
        - label: 我同意遵守项目的相关规定和要求
          required: true