title: "Hashkey Grant Application"
body:
  - type: markdown
    attributes:
      value: |
        # Basic Information
        Thank you for applying to Hashkey Grants! Please fill out the following information carefully.

  - type: dropdown
    id: grant-type
    attributes:
      label: Grant Type
      description: Select the type of grant you're applying for
      options:
        - Session 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Contact Information

  - type: input
    id: email
    attributes:
      label: Email
      placeholder: Your email address
    validations:
      required: true

  - type: input
    id: telegram
    attributes:
      label: Telegram
      placeholder: Your Telegram handle

  - type: input
    id: twitter
    attributes:
      label: X/Twitter Handle
      placeholder: Your Twitter handle

  - type: input
    id: discord
    attributes:
      label: Discord/Community
      placeholder: Your Discord or community information

  - type: markdown
    attributes:
      value: |
        # Project Details

  - type: textarea
    id: previous-application
    attributes:
      label: Previous Application
      description: If this is a resubmission, please provide the link to the previous application and explain the main improvements. If not, please write N/A
      placeholder: Previous application details or N/A
    validations:
      required: true

  - type: textarea
    id: code-audit
    attributes:
      label: Code Audit
      description: Has your project undergone a code audit?
      placeholder: Please provide code audit details
    validations:
      required: true

  - type: textarea
    id: project-info
    attributes:
      label: Project Information
      description: Please answer the following questions
      placeholder: |
        1. Project Description and Objectives:
        2. Success Potential:
           - Explain why your project is likely to succeed (consider market demand, technical feasibility, and team capability)
        3. Mission Alignment:
           - Describe how your project aligns with Hashkey's goals
        4. Innovation:
           - Highlight what makes your project unique or innovative
        5. Is it open source?
        6. Free or fee-based for end users?
        7. Interoperability with Hashkey ecosystem:
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Market Analysis

  - type: textarea
    id: market-analysis
    attributes:
      label: Market Analysis
      description: Please answer the following questions
      placeholder: |
        1. Competitors and Differentiation:
        2. Current User Base and Estimation Method:
    validations:
      required: true

  - type: input
    id: wallet-address
    attributes:
      label: Recipient Address
      description: Wallet address for receiving funds
      placeholder: 0x...
    validations:
      required: true

  - type: textarea
    id: budget-plan
    attributes:
      label: Budget and Plan
      description: Please answer the following questions
      placeholder: |
        1. Grant Size and Justification:
        2. Project Execution Plan (Roadmap):
        3. Token Distribution (Percentages and Initiatives):
        4. Token Distribution Timeline:
        5. Post-Incentives Sustainability:
        6. Additional Accountability Info (Smart Contract Addresses, Wallet Addresses, etc.):
    validations:
      required: true

  - type: textarea
    id: hashkey-relationship
    attributes:
      label: Hashkey Relationship
      description: Please answer the following questions
      placeholder: |
        1. Problem Solved for Hashkey:
        2. Value Proposition:
        3. Growth Potential for Hashkey:
        4. Commitment to Building on Hashkey:
        5. Deployment Status:
    validations:
      required: true

  - type: textarea
    id: milestones
    attributes:
      label: Milestones
      description: Please list your project's key milestones
      placeholder: |
        1. Milestone 1: [Description and Timeline]
        2. Milestone 2: [Description and Timeline]
        3. Milestone 3: [Description and Timeline]
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Terms Confirmation
      options:
        - label: I confirm that all information provided is true and accurate
          required: true
        - label: I understand and agree to comply with the grant policies
          required: true
        - label: I understand the KYC requirements
          required: true
        - label: I confirm token distribution complies with legal requirements
          required: true